// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/joao-carmo/blx/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// MockCatalogRepository is an autogenerated mock type for the CatalogRepository type
type MockCatalogRepository struct {
	mock.Mock
}

type MockCatalogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogRepository) EXPECT() *MockCatalogRepository_Expecter {
	return &MockCatalogRepository_Expecter{mock: &_m.Mock}
}

// GetHoldings provides a mock function with given fields: ctx, id
func (_m *MockCatalogRepository) GetHoldings(ctx context.Context, id string) ([]service.Holding, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetHoldings")
	}

	var r0 []service.Holding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]service.Holding, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []service.Holding); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Holding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_GetHoldings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHoldings'
type MockCatalogRepository_GetHoldings_Call struct {
	*mock.Call
}

// GetHoldings is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCatalogRepository_Expecter) GetHoldings(ctx interface{}, id interface{}) *MockCatalogRepository_GetHoldings_Call {
	return &MockCatalogRepository_GetHoldings_Call{Call: _e.mock.On("GetHoldings", ctx, id)}
}

func (_c *MockCatalogRepository_GetHoldings_Call) Run(run func(ctx context.Context, id string)) *MockCatalogRepository_GetHoldings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCatalogRepository_GetHoldings_Call) Return(_a0 []service.Holding, _a1 error) *MockCatalogRepository_GetHoldings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_GetHoldings_Call) RunAndReturn(run func(context.Context, string) ([]service.Holding, error)) *MockCatalogRepository_GetHoldings_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function with given fields: ctx, id
func (_m *MockCatalogRepository) GetItem(ctx context.Context, id string) (*service.Item, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 *service.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*service.Item, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *service.Item); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type MockCatalogRepository_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCatalogRepository_Expecter) GetItem(ctx interface{}, id interface{}) *MockCatalogRepository_GetItem_Call {
	return &MockCatalogRepository_GetItem_Call{Call: _e.mock.On("GetItem", ctx, id)}
}

func (_c *MockCatalogRepository_GetItem_Call) Run(run func(ctx context.Context, id string)) *MockCatalogRepository_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCatalogRepository_GetItem_Call) Return(_a0 *service.Item, _a1 error) *MockCatalogRepository_GetItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_GetItem_Call) RunAndReturn(run func(context.Context, string) (*service.Item, error)) *MockCatalogRepository_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, params
func (_m *MockCatalogRepository) Search(ctx context.Context, params service.SearchParams) (*service.SearchResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *service.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.SearchParams) (*service.SearchResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.SearchParams) *service.SearchResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.SearchParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockCatalogRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - params service.SearchParams
func (_e *MockCatalogRepository_Expecter) Search(ctx interface{}, params interface{}) *MockCatalogRepository_Search_Call {
	return &MockCatalogRepository_Search_Call{Call: _e.mock.On("Search", ctx, params)}
}

func (_c *MockCatalogRepository_Search_Call) Run(run func(ctx context.Context, params service.SearchParams)) *MockCatalogRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.SearchParams))
	})
	return _c
}

func (_c *MockCatalogRepository_Search_Call) Return(_a0 *service.SearchResult, _a1 error) *MockCatalogRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_Search_Call) RunAndReturn(run func(context.Context, service.SearchParams) (*service.SearchResult, error)) *MockCatalogRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCatalogRepository creates a new instance of MockCatalogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogRepository {
	mock := &MockCatalogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
